FROM webhippie/python:latest-amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Ansible Doctor" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT [""]

ENV PY_COLORS=1

RUN apk update && \
  apk upgrade && \
  pip3 install -U pip ansible-doctor && \
  rm -rf /var/cache/apk/*
